### ISSUE TITLE
Checksums don't match for RC_2018-09 (while generating)

### ISSUE THREAD

**Issue by jeonggwanlee** [microsoft/dstc8-reddit-corpus#4]
Hi,
I got this error while generating reddit-dataset.(python scripts/reddit.py generate)

> ERROR: [pid 70798] Worker Worker(salt=701453871, workers=36, host=pixie, username=jglee, pid=68592) failed    DownloadRawFile(date=2018-09, filetype=comments)
Traceback (most recent call last):
>  File "/home/jglee/anaconda3/envs/dstc8-baseline/lib/python3.7/site-packages/luigi-2.8.8-py3.7.egg/luigi/worker.py", line 199, in run
>    new_deps = self._run_get_new_deps()
>  File "/home/jglee/anaconda3/envs/dstc8-baseline/lib/python3.7/site-packages/luigi-2.8.8-py3.7.egg/luigi/worker.py", line 141, in _run_get_new_deps
>    task_gen = self.task.run()
>  File "/home/jglee/anaconda3/envs/dstc8-baseline/lib/python3.7/site-packages/dstc8_reddit-0.1.0-py3.7.egg/dstc8_reddit/tasks/download.py", line 64, in run
>    raise RuntimeError(f"Checksums don't match for {'RC' if self.filetype == 'comments' else 'RS'}_{self.date}!")
> RuntimeError: Checksums don't match for RC_2018-09!

How can i solve this?

**Comment by jeonggwanlee** [comment]
This is my conda python library list.

# packages in environment at /home/jglee/anaconda3/envs/dstc8-baseline:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
attrs                     19.1.0                   pypi_0    pypi
blas                      1.0                         mkl
boto3                     1.9.210                  pypi_0    pypi
botocore                  1.12.210                 pypi_0    pypi
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py37_1
cffi                      1.12.3           py37h2e261b9_0
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
cudatoolkit               10.0.130                      0
cython                    0.29.12          py37he6710b0_0
docutils                  0.15.2                   pypi_0    pypi
fairseq                   0.6.2                    pypi_0    pypi
fasttext                  0.8.3                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
hypothesis                3.88.3                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.4                      243
iterable-queue            1.2.2                    pypi_0    pypi
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.13.2                   pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
lockfile                  0.12.2                   pypi_0    pypi
luigi                     2.8.8                    pypi_0    pypi
mkl                       2019.4                      243
mkl-service               2.0.2            py37h7b6447c_0
mkl_fft                   1.0.14           py37ha843d7b_0
mkl_random                1.0.2            py37hd81dba3_0
mldc                      0.0.1                     dev_0    <develop>
ncurses                   6.1                  he6710b0_1
ninja                     1.9.0            py37hfd86e86_0
nltk                      3.4.4                    pypi_0    pypi
numpy                     1.16.4           py37h7e9f1db_0
numpy-base                1.16.4           py37hde5b4d6_0
onnx                      1.5.0                    pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1
pandas                    0.25.0                   pypi_0    pypi
pip                       19.1.1                   py37_0
portalocker               1.5.1                    pypi_0    pypi
protobuf                  3.9.1                    pypi_0    pypi
pycparser                 2.19                     py37_0
pydantic                  0.32.2                   pypi_0    pypi
pytext-nlp                0.1.2                    pypi_0    pypi
python                    3.7.4                h265db76_1
python-daemon             2.1.2                    pypi_0    pypi
python-dateutil           2.8.0                    pypi_0    pypi
python-rapidjson          0.8.0                    pypi_0    pypi
pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
pytz                      2019.2                   pypi_0    pypi
readline                  7.0                  h7b6447c_5
regex                     2019.6.8                 pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
runstats                  1.8.0                    pypi_0    pypi
s3transfer                0.2.1                    pypi_0    pypi
sacrebleu                 1.3.7                    pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
sentencepiece             0.1.83                   pypi_0    pypi
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.29.0               h7b6447c_0
tabulate                  0.8.3                    pypi_0    pypi
tensorboardx              1.8                      pypi_0    pypi
tk                        8.6.8                hbc83047_0
torch                     1.0.1                    pypi_0    pypi
torchtext                 0.4.0                    pypi_0    pypi
tornado                   4.5.3                    pypi_0    pypi
tqdm                      4.34.0                   pypi_0    pypi
typing                    3.7.4                    pypi_0    pypi
typing-extensions         3.7.4                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
wheel                     0.33.4                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3

**Comment by jeonggwanlee** [comment]
When I tried to generate with "--small" option, make error below.

ERROR: [pid 16592] Worker Worker(salt=637226664, workers=36, host=pixie, username=jglee, pid=44372) failed    BuildDialogues(date=2017-11)
Traceback (most recent call last):
  File "/home/jglee/anaconda3/envs/dstc8-baseline/lib/python3.7/site-packages/luigi-2.8.8-py3.7.egg/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: FilterRawSubmissions_2017_11_30e5e4658e

**Comment by jeonggwanlee** [comment]
@aatkinson Could you give me some answer??

**Comment by aatkinson** [comment]
Same issue as https://github.com/microsoft/dstc8-reddit-corpus/issues/5
